//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeekGang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSVP
    {
        public int id { get; set; }
        public int meet_id { get; set; }
        public int user_id { get; set; }

        public string user_name { get; set; }
        public string status { get; set; }
    
        public virtual Meetup Meetup { get; set; }
        public virtual User User { get; set; }

        public RSVP()
        {
            status = "Pending";
        }
    }
}
